#!/bin/bash

set -o errexit
set -o nounset

# ADJUST THIS FOR YOUR SYSTEM
readonly DATABASE_DIR="/data/databases"

# handle input file
readonly INPUT_FILE=$(basename $1)
readonly INPUT_DIR=$(dirname $(readlink -f $1))
shift

if [ ! -d ${OUTPUT_DIR} ]; then
    mkdir ${OUTPUT_DIR}
fi

docker run \
    --volume ${DATABASE_DIR}:${CONTAINER_DB_DIR} \
    --detach=false \
    --rm \
    --user=$(id -u):$(id -g) \
    ianamunoz/docker-zcash \
    $@
